### ISSUE TITLE
Slow builds

### ISSUE THREAD

**Issue by shirakaba** [kabiroberai/node-swift#22]
Loving `node-swift`, just wish libraries compiled faster!

I find that a warm build with `node-swift rebuild [--debug]` is very slow (~18 seconds on a M3 Max for a small change made to a basic six-file project) compared `node-gyp` on an equivalent warm build for a project written in Objective-C++ (<3 seconds, if I recall correctly).

In the console logs, I see `node-swift rebuild` spending a fair amount of time recompiling a bunch of unchanged files that have been compiled previously, like `swift-syntax`. Is there any way builds could be made faster, perhaps by caching this work (if it isn't already) or precompiling some of the dependencies? Thanks!

**Comment by kabiroberai** [comment]
It's a bit difficult to do this as it currently stands, because SwiftPM doesn't have a good way to cache SwiftSyntax out of the box — see this Swift Forums thread: [Compilation extremely slow since macros adoption](https://forums.swift.org/t/compilation-extremely-slow-since-macros-adoption/67921). I'm actually working on a long-term solution in the form of [WebAssembly Macros](https://forums.swift.org/t/poc-improving-macro-build-times-with-webassembly/70967) but it might take a while before that's generally available.

However, note that this only applies to clean builds; incremental builds _do_ already benefit from caching. `node-swift rebuild` performs a clean build, but you can make it incremental using `node-swift build` instead. Let me know if that helps!

**Comment by shirakaba** [comment]
Oh man, that really does the trick. Think I tunnel-visioned in on `nodw-swift rebuild` as I just copied the example as-is. A warm run of `node-swift build --debug` now goes as fast as 0.33s. Thanks! 🥹
