### ISSUE TITLE
Building example takes a long time, every time

### ISSUE THREAD

**Issue by jameshfisher** [kabiroberai/node-swift#40]
```
npm exec node-swift  215.15s user 23.28s system 140% cpu 2:49.33 total
```

Most of the time is spent in

```
[26/33] Compiling NodeModuleSupport register.m
```

**Comment by kabiroberai** [comment]
The SwiftPM output is misleading, I believe it actually spends most of its time compiling swift-syntax (which is a [known upstream issue](https://forums.swift.org/t/compilation-extremely-slow-since-macros-adoption/67921).)

The fact that it's slow _every_ time is because we do a clean release build by default (which is something I've considered changing, open to input.) You can speed up subsequent builds a ton by instead running `npx node-swift build`.

**Comment by jameshfisher** [comment]
Sorry, yes, `build` is a bajillion times faster than `rebuild`! I'd make that the default, although I'm not sure of the tradeoffs. Thanks for your help!
